project:
  output-dir: ./docs/sv

book:
  title: "Moderna statistiska metoder"
  chapters:
    - index.qmd
  sidebar:
    contents: auto

bibliography: references.bib
lang: sv

format:
  html:
    theme: pulse
