project:
  output-dir: ./_site/fi

book:
  title: "Modernit m채채r채lliset menetelm채t"
  chapters:
    - index.qmd
  sidebar:
    contents: auto

bibliography: references.bib
lang: fi

format:
  html:
    theme: pulse
