project:
  output-dir: ./docs/fi

book:
  title: "Modernit määrälliset menetelmät"
  chapters:
    - index.qmd
    - part: src/fi/intro.qmd
  sidebar:
    contents: auto

bibliography: references.bib
lang: fi

format:
  html:
    theme: pulse
