---
title: Aloitus
date: last-modified
author:
- name: Oliver Saal
  orcid: 0000-0002-4870-0458
  url: https://osaal.github.io
  email: oliver.saal@pelastusopisto.fi
  corresponding: true
  affiliation:
    - name: Pelastusopisto
      department: Tutkimus-, kehittämis- ja innovaatiopalvelut
      city: Kuopio
      country: FI
      url: https://www.pelastusopisto.fi
keywords:
    - esipuhe
    - tarkoitus
    - sisältö
abstract: |
    Tervetuloa oppikirjaan "Modernit tilastolliset menetelmät". Aluksi käymme läpi, miksi kirja on olemassa, mitä se tulee sisältämään ja miten kirjan lukeminen toimii parhaiten.
license: "CC BY"
citation: true
---

Tervetuloa oppikirjaan! Avaamalla tämän oppikirjan olet aloittamassa uuden matkan tilastojen käytännön soveltamisessa, tai ainakin osoittamassa aikeesi tälle matkalle.

Tässä osiossa käyn läpi, miksi tämä kirja edes on olemassa: mitä tilastotieteestä tulisi oppia, kenen tulisi oppia tämä ja mistä syystä aikaisemmat teokset eivät ole riittäviä?

Käyn myös läpi miten tätä kirjaa suositellaan luettavaksi. Mitä sinun tulisi tietää ennen kirjan lukemista? Kuka voi lukea tämän kirjan? Mistä aloittaa?

# Miksi taas uusi kirja tilastotieteestä?

Oppikirjoja on pilvin pimein, ja niitä julkaistaan uusia joka vuosi. Oppimateriaalien kehittäminen onkin oma markkinansa, jossa kirjoittajia kannustetaan rahallisesti tuottamaan uusia, harvoin suuresti muokattuja painoksia aikaisemmista teoksista ja myymään niitä opiskelijoille ja yliopistokirjastoille.

Miksi sitten kirjoittaa taas uusi kirja tilastollisesta työskentelystä? Ennen kuin hyppään syvällisempiin syihin, haluan antaa kolme mielestäni itsestäänselvää syytä:

1.  Tämä kirja on ilmainen.
2.  Tämä kirja perustuu uusimpaan tutkimustietoon.
3.  Tätä kirjaa voidaan päivittää myös muiden toimesta jatkuvasti.

Olen ehkä radikaali, kun väitän, että oppimisen ei tulisi maksaa yksilölle. Näin kuitenkin ajattelen, ja tämän oppikirjan ilmaiseksi julkaiseminen on osa tätä ideologiaani. Samalla kun kerran tehdään, niin tehdään kunnolla: kirjan tiedot pohjautuvat uusimpiin kehityksiin psykometriikassa (ihmisen mittaamisen tieteessä). Jos ei kuitenkaan onnistuta kerralla, niin verkkokirjamuoto ja avoin julkaisu mahdollistaa kirjan päivittämisen ja korjaamisen milloin tahansa kenen tahansa -- kyllä, myös sinun! -- toimesta.

## Modernit menetelmät vaativat modernin käsittelyn {#sec-fi-intro-motivation-1}

Tilastotiede kehittyy erittäin nopeasti. Tätä kehitystä on nopeuttanut varsinkin 90- ja 2000-luvun tietotekniset kehitykset, jolloin tietokoneista on tullut moninkertaisesti tehokkaampia. Ennen vanhaan tilastotiedettä opeteltiin matemaattisten kaavojen ja suurten taulukkojen avulla, nykyään näihin ei juurikaan kosketa käytännön työssä.

Tilastollinen opetus ei kuitenkaan ole aina seurannut tätä kehitystä, varsinkaan suomeksi. Pieni maamme ja kielemme ei välttämättä mahda sisällensä tarpeeksi tilastotieteestä, tieteen käytännön tekemisestä sekä tiedeviestinnästä samanaikaisesti kiinnostuneita yksilöitä, jotta uusimmat kehitykset saataisiin opetuskäytäntöön.

Jos avaan tällä hetkellä käytännössä minkä tahansa suomenkielisen tilastollisen oppikirjan, voin katsomattakin veikata, että sisältö seuraa kuta kuinkin seuraavaa järjestystä:

1.  Yksi lyhyt luku, mitä tilastoilla voidaan tehdä
2.  Muutama luku mittaustasoista, ehkä jopa luku kyselytutkimuksesta
3.  Sijaintiluvut ja hajontaluvut
4.  Ristiintaulukointi
5.  Korrelaatio, varianssianalyysi (vain yksinkertainen, luultavasti vain ryhmien välinen ANOVA)
6.  Vähimmäisen neliön regressioanalyysi, logistinen regressioanalyysi
7.  Eksploratiivinen faktorianalyysi ja PCA-menetelmä
8.  Tulosten raportoiminen

Aloittelijalle nämä eivät välttämättä sano mitään, mutta varttuneemmalle tutkijalle listaus pitäisi olla aika tuttu. **Sillä näitä samoja asioita on opetettu jo melkein viisikymmentä vuotta.**

Kuitenkaan tuosta listasta ei nykypäivänä saa työkalupakkia tieteelliseen julkaisuun, varsinkaan yhteiskunta- ja ihmistieteissä! Lukija voi kokeilla julkaista vain OLS-regressioon tai ANOVA-malliin pohjautuvan tutkimusartikkelin modernissa aikakauslehdessä -- uskallan väittää, että artikkeli tulee takaisin bumerangina, jos ei analyysiin lisätä muita osuuksia.

On yksinkertainen fakta, ettei nämä menetelmät enää yksinään riitä. Bivariaatit (kahden muuttujan väliset) mallit kehitettiin aikana, jolloin kynä ja paperi hallitsi tilastotiedettä, ja mittauspisteitä oli kymmeniä, ei tuhansia. Monessa tieteenhaarassa tiedämme myös tässä vaiheessa niin paljon perusasioista, ettei nykyisiä monimutkasia muuttujasuhteita enää voida testata yksinkertaisilla kaksi- ja monimuuttujamalleilla.

## Tilastotiede pohjautuu yhteen kaavioon {#sec-fi-intro-motivation-2}

Toinen ongelma tilastotieteessä koskee tiedettä laajemmin. Eri tilastolliset menetelmät tulevat eri tieteenaloilta -- esimerkkinä varianssianalyysi kehitettiin biologiassa, logistinen regressioanalyysi sosiologiassa, ja rakenneyhtälömallit psykologiassa, kauppatieteissä ja pedagogiikassa.

Eri kehitysurien takia tilastotiede käyttää melkein järkyttäviä määriä eri sanoja ja malleja, *jotka tarkoittavat samaa asiaa!* Rakkaalla lapsella on monta nimeä, ja tilastotieteessä rakastetaan lapsiaan suuresti.

Tämä kehitys heikentää luonnollisesti uuden opiskelijan oppimismahdollisuuksia -- miksi hänen pitäisi oppia viisi eri termiä virhemittaukselle? Toiseksi tieteen monimuotoisuus on omiaan häivyttämään menetelmien samankaltaisuutta.

## Rakenneyhtälömallintamista koko matkan {#sec-fi-intro-motivation-3}

On tilastotieteellinen loukkaus väittää, että jonkun henkilön malli on vain erityistapaus minun omasta yleismallistani. Kuitenkin näin usein on: t-testi on vain erityistapaus varianssianalyysista, varianssianalyysi on vain erityistapaus regressiosta, ja regressio on vain erityistapaus rakenneyhtälömalleista.

Tätä suhdetta kutsutaan **yleiseksi lineaariseksi malliksi**. Toisin sanoen: kaikki lineaariset mallit ovat käytännössä sama asia. Saat saman tuloksen varianssianalyysista, jossa on vain kaksi luokkaa ennustavassa muuttujassa, kuin saisit t-testistä näillä kahdella luokalla, sillä testi on käytännössä sama. Voit tuottaa OLS-regression tulokset ANOVA-mallilla hyödyntäen kovariaatteja, ja ANOVA-mallin voit toistaa OLS-regressiossa dummy-muuttujilla. Ja pohjalla kaikki perustuu varianssi-kovarianssi-matriisien sekä keskiarvovektoreiden analyysiin, eli rakenneyhtälömallintamiseen.

Näiden sanojen ei tarvitse merkitä lukijalle tässä hetkessä yhtään mitään muuta, kuin seuraavaa:

> Tämän kirjan tarkoituksena on esittää tilastotiede yhdestä yhtenäisestä paradigmasta, rakenneyhtälömallintamisen näkökulmasta.

# Kirjan sisältö

Kirja on jaettu osioihin, jotka ovat jaettuja lukuihin ja alalukuihin. Osiot on sijoitettu kumulatiiviseen järjestykseen: kun lukija on ymmärtänyt ja sisäistänyt yhden osion, hänellä on tarvittavat taustatiedot seuraavalle osiolle. Suosittelen siksi aloittelijalle, että aloitat kirjan alusta ja jatkat suoraan eteenpäin. Jos osaat jo joitain tilastollisia menetelmiä, voit hypätä niiden lukujen yli.

Ensimmäisen osion nimi on **Tilastollinen ajattelu**, ja keskittyy tilastotieteen teoreettisiin perusteisiin. Miksi käytämme tilastoja ylipäätäänsä? Mitä uutta me voimme saada aikaiseksi tilastoilla, ja mitä me emme voi sanoa tilastoilla?

Toinen osio käsittelee **tiedonkeruuta**. Tilastotiedettä ei voi tehdä ilman tietoa, eli dataa, mutta dataa voi kerätä hyvin monella eri tavalla. Tilastotieteessä on myös sanonta "roskaa sisään, roskaa ulos" -- jos tiedonkeruu on jollain tavalla puutteellinen, mikään menetelmä ei voi pelastaa tutkimusta. Osiossa käsitellään yleisimpiä tiedonkeruumenetelmiä kuten poikittaistutkimuksia ja kokeellisia asetelmia, mutta myös moderneja menetelmiä kuten intensiiviset pitkittäisasetelmat ja ekologiset momenttitutkimukset. Osiossa painotan erityisesti mittausvirheen mallia, eli jokaista asetelmaa tarkastellaan mahdollisten virheiden ja vääristymien näkökulmasta.

Kolmas osio, **Perusmenetelmät**, käsittelee kirjassa ensimmäistä kertaa numeroita ja niiden laskemista. Kyllä, luit oikein, vasta kolmannessa osiossa käsitellään tilastoja käytännössä. Osiossa käydään läpi sijainti- ja hajontaluvut sekä tulosten graafinen esittely.

Kolmanteen osioon liittyy myös ensimmäinen tärkeä liiteluku, **Tilastolliset työkalut**. Jotta tutkija voi laskea tilastoja, hän tarvitsee nykypäivänä tietokoneohjelman. Näitä ohjelmia on pilvin pimein, mutta keskityn tässä kirjassa kahteen ilmaiseen vaihtoehtoon: R-ohjelmointikieli sekä Jamovi-tilastotyökalu. Yhteiskunta- ja terveystieteistä tuttu SPSS-ohjelma jää tästä kirjasta pois, sillä työkalu on maksullinen eikä tue useita kirjassa esiteltyjä menetelmiä. Suosittelen vahvasti lukijalle, että hän valitsee tässä vaiheessa yhden työkalun, jolla tehdä kirjan harjoitustehtäviä -- työkalun oppiminen on itsessään raskasta, eikä tilastollista oppimisprosessia kannata tehdä yhtään vaikeammaksi usean työkalun limittäiskäytöllä.

Neljäs osio palaa hetkellisesti takaisin teorian maailmaan ja käsittelee **tilastollista päättelyä**. Tässä osiossa esitän nollahypoteesin käsitteen ja frekvenssitilastotieteen perusteet.

Viides osio jättää teorian taakseen ja käsittelee perinteisiä **muuttujamalleja**. Käsittelemme t-testin, varianssianalyysin, korrelaation sekä regressioanalyysin.

Kuudennessa osiossa lukijalla on jo tarpeeksi taustatietoja ymmärtääkseen **rakenneyhtälömallintamisen**. Tämä osio on isoin kaikista, sillä sen luvut suorittavat kirjan perustehtävää: opettaa lukijalle rakenneyhtälömallin logiikan ja käytännön, jotta hän voisi soveltaa näitä omassa tutkimuksessaan.

# Lähteet {#sec-fi-intro-references}

::: {#refs}
:::

